import { MD3LightTheme, type MD3Theme } from 'react-native-paper';
import { TYPOGRAPHY } from './tokens';

export const COLORS = {
  primary: '#FF4D4D',
  primaryPressed: '#E63E3E',
  primaryDark: '#B4232D',
  onPrimary: '#FFFFFF',
  primaryContainer: '#FFE5E5',
  onPrimaryContainer: '#68151B',

  secondary: '#2DD4BF',
  secondaryPressed: '#22B8A6',
  secondaryDark: '#0F766E',
  onSecondary: '#073B35',
  secondaryContainer: '#D9F8F3',
  onSecondaryContainer: '#0A4F47',

  background: '#F3F6F5',
  surface: '#FFFFFF',
  surfaceSubtle: '#EAEFEE',
  surfacePressed: '#E3EAE8',

  text: '#172423',
  textMuted: '#60706E',
  textSubtle: '#72817F',
  border: '#D7E0DE',
  borderStrong: '#879692',

  success: '#247451',
  successContainer: '#E0F3EA',
  warning: '#925300',
  warningContainer: '#FFF1D6',
  error: '#8F1D2C',
  errorContainer: '#FCE8EA',
  onErrorContainer: '#68151B',
  info: '#246B81',
  infoContainer: '#E1F2F6',

  white: '#FFFFFF',
  black: '#000000',
} as const;

export const MODULE_COLORS = {
  inventory: { color: '#0F766E', softColor: '#CCFBF1' },
  purchases: { color: '#9A4A08', softColor: '#FFEDD5' },
  pos: { color: '#1D4ED8', softColor: '#DBEAFE' },
  customers: { color: '#BE185D', softColor: '#FCE7F3' },
  accounting: { color: '#3F6212', softColor: '#ECFCCB' },
  access: { color: '#475569', softColor: '#E2E8F0' },
  settings: { color: '#6D28D9', softColor: '#EDE9FE' },
} as const;

export const paperTheme = {
  ...MD3LightTheme,
  roundness: 3,
  fonts: {
    ...MD3LightTheme.fonts,
    headlineLarge: { ...MD3LightTheme.fonts.headlineLarge, ...TYPOGRAPHY.title },
    headlineMedium: { ...MD3LightTheme.fonts.headlineMedium, ...TYPOGRAPHY.title },
    headlineSmall: { ...MD3LightTheme.fonts.headlineSmall, ...TYPOGRAPHY.title },
    titleLarge: { ...MD3LightTheme.fonts.titleLarge, ...TYPOGRAPHY.subtitle },
    titleMedium: { ...MD3LightTheme.fonts.titleMedium, ...TYPOGRAPHY.subtitle },
    titleSmall: { ...MD3LightTheme.fonts.titleSmall, ...TYPOGRAPHY.subtitle },
    bodyLarge: { ...MD3LightTheme.fonts.bodyLarge, ...TYPOGRAPHY.body },
    bodyMedium: { ...MD3LightTheme.fonts.bodyMedium, ...TYPOGRAPHY.body },
    bodySmall: { ...MD3LightTheme.fonts.bodySmall, ...TYPOGRAPHY.metadata },
    labelLarge: { ...MD3LightTheme.fonts.labelLarge, ...TYPOGRAPHY.body, fontWeight: '700' },
    labelMedium: { ...MD3LightTheme.fonts.labelMedium, ...TYPOGRAPHY.metadata, fontWeight: '700' },
    labelSmall: { ...MD3LightTheme.fonts.labelSmall, ...TYPOGRAPHY.metadata, fontWeight: '700' },
  },
  colors: {
    ...MD3LightTheme.colors,
    primary: COLORS.primary,
    primaryContainer: COLORS.primaryContainer,
    secondary: COLORS.secondary,
    secondaryContainer: COLORS.secondaryContainer,
    tertiary: COLORS.info,
    tertiaryContainer: COLORS.infoContainer,
    surface: COLORS.surface,
    surfaceVariant: COLORS.surfaceSubtle,
    surfaceDisabled: 'rgba(23,36,35,0.12)',
    background: COLORS.background,
    error: COLORS.error,
    errorContainer: COLORS.errorContainer,
    onPrimary: COLORS.onPrimary,
    onPrimaryContainer: COLORS.onPrimaryContainer,
    onSecondary: COLORS.onSecondary,
    onSecondaryContainer: COLORS.onSecondaryContainer,
    onTertiary: COLORS.white,
    onTertiaryContainer: '#113D49',
    onSurface: COLORS.text,
    onSurfaceVariant: COLORS.textMuted,
    onSurfaceDisabled: 'rgba(23,36,35,0.38)',
    onError: COLORS.white,
    onErrorContainer: COLORS.onErrorContainer,
    onBackground: COLORS.text,
    outline: COLORS.borderStrong,
    outlineVariant: COLORS.border,
    inverseSurface: COLORS.text,
    inverseOnSurface: COLORS.background,
    inversePrimary: '#FFB8B8',
    shadow: COLORS.black,
    scrim: COLORS.black,
    backdrop: 'rgba(23,36,35,0.42)',
    elevation: {
      level0: 'transparent',
      level1: '#F9FBFA',
      level2: '#F5F9F8',
      level3: '#EFF6F4',
      level4: '#ECF4F2',
      level5: '#E7F2EF',
    },
  },
} satisfies MD3Theme;
